sushack/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin

from .views import Home


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', Home.as_view()),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
    {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
)
urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
    {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
)

sushack/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from feincms.content.richtext.models import RichTextContent
from feincms.module.page.models import Page


class Attendee(models.Model):
    event = models.ForeignKey('Event', blank=True)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    github_username = models.CharField(max_length=255, null=True, blank=True)
    twitter_username = models.CharField(max_length=255, null=True, blank=True)
    project = models.TextField(null=True, blank=True)
    attended = models.BooleanField(default=False)

    class Meta:
        ordering = ['pk']
        unique_together = ('email', 'event')

    def __unicode__(self):
        return self.name


class EventManager(models.Manager):
    def current(self):
        try:
            return self.get_query_set().filter(current=True)[0]
        except IndexError:
            return self.get_query_set().none()


class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    where = models.TextField()
    start = models.DateTimeField()
    finish = models.DateTimeField()
    current = models.BooleanField(default=False)

    objects = EventManager()

    class Meta:
        ordering = ['start']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('event-detail', pk=self.pk)

class MailingListPerson(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)

    def __unicode__(self):
        return self.name


class Sponsor(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=512, unique=True)
    image = models.FileField(upload_to='img')

    def __unicode__(self):
        return self.name


Page.register_templates(
    {
        'key': '1col',
        'title': _('One column'),
        'path': 'base.html',
        'regions': (
            ('main', _('Main content')),
        ),
    },
)
Page.create_content_type(RichTextContent)

sushack/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Submit, Div
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Attendee, MailingListPerson


class MailingListForm(forms.ModelForm):
    class Meta:
        model = MailingListPerson

    helper = FormHelper()
    helper.form_method = 'post'
    helper.layout = Layout(
        Fieldset('',
            Field('email', placeholder='Email address'),
            Field('name', placeholder='Name'),
            Submit('submit', _('Sign Up!'), css_class='submit'),
        )
    )


class SignUpForm(forms.ModelForm):
    class Meta:
        fields = (
            'name',
            'email',
            'github_username',
            'twitter_username',
            'project',
        )
        model = Attendee

    helper = FormHelper()
    helper.form_method = 'post'
    helper.layout = Layout(
        Div(
            Div(
                Field('name', placeholder='Name*'),
                Field('email', placeholder='Email address*'),
                Field(
                    'github_username',
                    placeholder='Your GitHub username',
                    label='GitHub username (Optional)',
                    ),
                Field(
                    'twitter_username',
                    placeholder='Your Twitter username (without the @)',
                    label='Twitter username (Optional)',
                    ),
                Submit('submit', _('Sign Up!'), css_class='submit'),
                css_class='pull-left form-elements-left',
            ),
            Div(
                Field(
                    'project',
                    rows='5',
                    placeholder='What would you like to work on?',
                    label='What would you like to work on?',
                    ),
                css_class='pull-right form-elements-right',
            ),
            css_class='signup-form',
        )
    )

sushack/views.py
from django.contrib import messages
from django.views.generic import CreateView

from .forms import MailingListForm
from .forms import SignUpForm
from .models import Event
from .models import Sponsor


class Home(CreateView):
    @property
    def success_url(self):
        if Event.objects.current():
            url = '/#attendees'
        else:
            url = '/'
        return url

    @property
    def form_class(self):
        if Event.objects.current():
            form_class_ = SignUpForm
        else:
            form_class_ = MailingListForm
        return form_class_

    template_name = 'home.html'

    def form_valid(self, form):
        if Event.objects.current():
            return self._signup_form_valid(form)
        else:
            return self._mailing_list_form_valid(form)

    def _mailing_list_form_valid(self, form):
        msg = "Thanks for signing up for emails, we'll send you details about any future SusHack events."
        messages.info(self.request, msg)
        return super(Home, self).form_valid(form)

    def _signup_form_valid(self, form):
        self.event = Event.objects.current()
        msg = "Thanks for signing up, we'll email you more details closer to the date."
        messages.info(self.request, msg)
        form.instance.event = self.event
        return super(Home, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['event'] = Event.objects.current()
        context['sponsors'] = Sponsor.objects.all()
        return context

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block page_title %}SusHack{% endblock %}</title>
        <meta name="description" content="SusHack is a one-day hack event based around sustainability, hosted in Oxford.">
        <meta name="viewport" content="width=device-width">
        <!--[if lt IE 9]>
           <script>
              document.createElement('header');
              document.createElement('nav');
              document.createElement('section');
              document.createElement('article');
              document.createElement('aside');
              document.createElement('footer');
           </script>
        <![endif]-->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Raleway:400,700">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
        <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.png">
    </head>
    <body>
        <div class="page-wrapper">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li>
                            <span class="close">&times;</span>
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% block content %}
            {% endblock content %}
        </div>

        {% block js %}
        {% endblock js %}

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-43559920-1', 'sushack.co.uk');
          ga('send', 'pageview');

        </script>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load gravatar %}

{% block page_title %}
SusHack Oxford - The sustainability oriented hack day
{% endblock page_title %}

{% block content %}
    <header class="banner">
        <div class="section-inner">
            <h1>SusHack_ Oxford</h1>
        </div>
    </header>
    <section class="section what">
        <div class="section-inner">
            <h2>
                What is SusHack?
            </h2>
            <div class="pull-left">
                <p>
                    SusHack is a <strong>free</strong> one-day hack day that helps developers get together to create solutions to sustainability problems using their skills in development and lots of coffee.
                </p>
                <p>
                    The aim of the hack day isn't to deliver any polished software, but to rapidly take something from an idea through to a working/demonstrable piece of software.
                </p>
                <p>
                    SusHack is completely free to attend. We've got the space, food/refreshments and WiFi, all you need to bring is yourself and your laptop.
                </p>
            </div>
            <div class="pull-right">
                <p>
                    What kind of things can we make?
                </p>
                <ul>
                    <li>
                        Google Maps route carbon footprint calculator extension, to easily make informed decisions about travel.
                    </li>
                    <li>
                        Calendar to tell you when food you've bought is due to expire, to reduce food wastage.
                    </li>
                    <li>
                        An application for Raspberry Pi to find which bin week it is, then indicate with LEDs next to bins.
                    </li>
                    <li>
                        Or anything you like.
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section class="section when">
        <div class="section-inner">
            <h2>
                When was SusHack?
            </h2>
            <p class="centered">
                SusHack took place on <strong>{{ event.start|date:"l d F Y" }}</strong>, at <strong>{{ event.start|date:"H:i" }}</strong>.
            </p>
        </div>
    </section>
    <section class="section where">
        <div class="section-inner">
            <h2>
                Where was SusHack held?
            </h2>
            <p class="centered">
                SusHack was hosted by <a href="http://2degreesnetwork.com" target="_blank">2degrees</a> at their offices in Summertown.
            </p>
            <div id="map_canvas"></div>
            <p class="centered">
                <a href="https://www.google.co.uk/maps?q={{ event.where | urlencode }}" target="_blank">
                    {{ event.where }}
                </a>
            </p>
        </div>
    </section>
    <section class="section schedule">
        <div class="section-inner">
            <h2>
                Schedule
            </h2>
            <pre>|--------|----------------|
| Time   | Activity       |
|--------|----------------|
| 09:00  | Doors open     |
| 09:30  | Intro/pastries |
| 10:00  | Teaming        |
| 13:00  | Burritos       |
| 18:00  | Pizza          |
| 19:30  | Showcase       |
| 20:30  | Leave          |
|--------|----------------|</pre>
        </div>
    </section>
    {% if event.attendee_set %}
        <section class="section who" id="attendees">
            <div class="section-inner">
                <h2>
                    Who went?
                </h2>
                {% if event.attendee_set.all %}
                <ul class="attendees-list">
                    {% for attendee in event.attendee_set.all %}
                        {% if attendee.attended %}
                            <li class="attendee">
                                <img
                                    src="{% gravatar_for_email attendee.email %}"
                                    title="{{ attendee.name }}"
                                    width="80"
                                    height="80"
                                />
                                {% if attendee.github_username or attendee.twitter_username %}
                                <ul>
                                    {% if attendee.github_username %}
                                    <li class="github">
                                        <a href="http://github.com/{{ attendee.github_username }}" target="_blank">
                                            @{{ attendee.github_username }}
                                        </a>
                                    </li>
                                    {% endif %}
                                    {% if attendee.twitter_username %}
                                    <li class="twitter">
                                        <a href="http://twitter.com/{{ attendee.twitter_username }}" target="_blank">
                                            @{{ attendee.twitter_username }}
                                        </a>
                                    </li>
                                    {% endif %}
                                </ul>
                                {% endif %}
                                <h5>
                                    {{ attendee.name }}
                                </h5>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>

                {% else %}
<pre class="centered">
Nobody is going :(
</pre>
                {% endif %}
            </div>
        </section>
    {% endif %}
    {% if sponsors %}
        <section class="section sponsors">
            <div class="section-inner">
                <h2>
                    Sponsors
                </h2>
                <ul class="sponsors-list">
                    {% for sponsor in sponsors.all %}
                        <li class="sponsor">
                            <a href="{{ sponsor.url }}" target="_blank">
                                <img src="{{ MEDIA_URL }}{{ sponsor.image }}" alt="{{ sponsor.name }}" />
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
    {% endif %}
{% endblock content %}

{% block js %}

    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="{{ STATIC_URL }}js/jquery-1.8.0.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.ui.map.full.min.js"></script>
    <script>

    $(function() {
        $('#map_canvas').gmap({
                scrollwheel: false,
                navigationControl: true,
                mapTypeControl: false,
                scaleControl: false,
                draggable: false,
                disableDoubleClickZoom: true,
                disableDefaultUI: true,
                mapTypeId: google.maps.MapTypeId.TERRAIN
        }).bind('init', function() {
            var image = new google.maps.MarkerImage(
                '{{ STATIC_URL }}img/marker.png',
                new google.maps.Size(40, 40),
                new google.maps.Point(0, 0),
                new google.maps.Point(15, 40)
            );

            $('#map_canvas').gmap('addMarker', {
                'position': new google.maps.LatLng('51.776557','-1.264402'),
                'bounds': true,
                'icon': image
            });
        });
        $('a[href^="#"]').on('click', function (e) {
            e.preventDefault();

            $('html, body').animate({
                scrollTop: $($(this).attr('href')).offset().top
            }, 500);
        });

        $('.close').on('click', function () {
            $(this).closest('.messages').fadeOut();
        });
    });
    </script>
{% endblock js %}

templates/home_old.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load gravatar %}

{% block page_title %}
SusHack Oxford - The sustainability oriented hack day
{% endblock page_title %}

{% block content %}
    <header class="banner">
        <div class="section-inner">
            <h1>SusHack_ Oxford</h1>
        </div>
    </header>
    <section class="section what">
        <div class="section-inner">
            <h2>
                What is SusHack?
            </h2>
            <div class="pull-left">
                <p>
                    SusHack is a <strong>free</strong> one-day hack day that helps developers get together to create solutions to sustainability problems using their skills in development and lots of coffee.
                </p>
                <p>
                    The aim of the hack day isn't to deliver any polished software, but to rapidly take something from an idea through to a working/demonstrable piece of software.
                </p>
                <p>
                    SusHack is completely free to attend. We've got the space, food/refreshments and WiFi, all you need to bring is yourself and your laptop.
                </p>
            </div>
            <div class="pull-right">
                <p>
                    What kind of things can we make?
                </p>
                <ul>
                    <li>
                        Google Maps route carbon footprint calculator extension, to easily make informed decisions about travel.
                    </li>
                    <li>
                        Calendar to tell you when food you've bought is due to expire, to reduce food wastage.
                    </li>
                    <li>
                        An application for Raspberry Pi to find which bin week it is, then indicate with LEDs next to bins.
                    </li>
                    <li>
                        Or anything you like. You can specify any ideas you've got for things to make on the <a href="#form">sign up form</a>.
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section class="section when">
        <div class="section-inner">
            <h2>
                When is SusHack?
            </h2>
            <p class="centered">
                SusHack will take place on <strong>{{ event.start|date:"l d F Y" }}</strong>, at <strong>{{ event.start|date:"H:i" }}</strong>.
            </p>
        </div>
    </section>
    <section class="section where">
        <div class="section-inner">
            <h2>
                Where is SusHack going to be held?
            </h2>
            <p class="centered">
                SusHack will be hosted by <a href="http://2degreesnetwork.com" target="_blank">2degrees</a> at their offices in Summertown.
            </p>
            <div id="map_canvas"></div>
            <p class="centered">
                <a href="https://www.google.co.uk/maps?q={{ event.where | urlencode }}" target="_blank">
                    {{ event.where }}
                </a>
            </p>
        </div>
    </section>
    <section class="section schedule">
        <div class="section-inner">
            <h2>
                Schedule
            </h2>
            <pre>|--------|----------------|
| Time   | Activity       |
|--------|----------------|
| 09:00  | Doors open     |
| 09:30  | Intro/pastries |
| 10:00  | Teaming        |
| 13:00  | Burritos       |
| 18:00  | Pizza          |
| 19:30  | Showcase       |
| 20:30  | Leave          |
|--------|----------------|</pre>
        </div>
    </section>
    <section class="section how" id="form">
        <div class="section-inner">
            <h2>
                How can I take part?
            </h2>
            <p>
                Sign up using the form below, and follow <a href="http://twitter.com/sushack_" target="_blank">@SusHack_</a> on Twitter, to hear any updates from us as they happen.
            </p>
            {% crispy form %}
        </div>
    </section>
    {% if event.attendee_set %}
        <section class="section who" id="attendees">
            <div class="section-inner">
                <h2>
                    Who is going?
                </h2>
                {% if event.attendee_set.all %}
                <ul class="attendees-list">
                    {% for attendee in event.attendee_set.all %}
                        <li class="attendee">
                            <img
                                src="{% gravatar_for_email attendee.email %}"
                                title="{{ attendee.name }}"
                                width="80"
                                height="80"
                            />
                            {% if attendee.github_username or attendee.twitter_username %}
                            <ul>
                                {% if attendee.github_username %}
                                <li class="github">
                                    <a href="http://github.com/{{ attendee.github_username }}" target="_blank">
                                        @{{ attendee.github_username }}
                                    </a>
                                </li>
                                {% endif %}
                                {% if attendee.twitter_username %}
                                <li class="twitter">
                                    <a href="http://twitter.com/{{ attendee.twitter_username }}" target="_blank">
                                        @{{ attendee.twitter_username }}
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                            {% endif %}
                            <h5>
                                {{ attendee.name }}
                            </h5>
                        </li>
                    {% endfor %}
                </ul>
                <p>
                    Signed up, but seeing a blue G for your photo? Make sure you used an email address associated with <a href="https://en.gravatar.com/" target="_blank">Gravatar</a>, and set your profile picture there.
                </p>
                <p>
                    Want to change any of the details you've submitted? Let us know via <a href="http://twitter.com/sushack_" target="_blank">Twitter</a> or <a href="mailto:hello@sushack.co.uk" target="_blank">E-mail us</a>.
                </p>
                <h3>
                    Can't make it to this SusHack?
                </h3>
                <p>
                    If this SusHack goes well we'll hold future events, so keep your eyes peeled for that. If you're looking for other technology-based events in Oxford, check out <a href="http://www.digitaloxford.com" target="_blank">Digital Oxford</a>.
                </p>

                {% else %}
<pre class="centered">
Nobody is going :(
</pre>
                {% endif %}
            </div>
        </section>
    {% endif %}
    {% if sponsors %}
        <section class="section sponsors">
            <div class="section-inner">
                <h2>
                    Sponsors
                </h2>
                <ul class="sponsors-list">
                    {% for sponsor in sponsors.all %}
                        <li class="sponsor">
                            <a href="{{ sponsor.url }}" target="_blank">
                                <img src="{{ MEDIA_URL }}{{ sponsor.image }}" alt="{{ sponsor.name }}" />
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
    {% endif %}
{% endblock content %}

{% block js %}

    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="{{ STATIC_URL }}js/jquery-1.8.0.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.ui.map.full.min.js"></script>
    <script>

    $(function() {
        $('#map_canvas').gmap({
                scrollwheel: false,
                navigationControl: true,
                mapTypeControl: false,
                scaleControl: false,
                draggable: false,
                disableDoubleClickZoom: true,
                disableDefaultUI: true,
                mapTypeId: google.maps.MapTypeId.TERRAIN
        }).bind('init', function() {
            var image = new google.maps.MarkerImage(
                '{{ STATIC_URL }}img/marker.png',
                new google.maps.Size(40, 40),
                new google.maps.Point(0, 0),
                new google.maps.Point(15, 40)
            );

            $('#map_canvas').gmap('addMarker', {
                'position': new google.maps.LatLng('51.776557','-1.264402'),
                'bounds': true,
                'icon': image
            });
        });
        $('a[href^="#"]').on('click', function (e) {
            e.preventDefault();

            $('html, body').animate({
                scrollTop: $($(this).attr('href')).offset().top
            }, 500);
        });

        $('.close').on('click', function () {
            $(this).closest('.messages').fadeOut();
        });
    });
    </script>
{% endblock js %}